In [1]:
import pandas as pd

In [2]:
ks200 = pd.read_csv('../../../1. 데이터셋/train_data/KOSPI200.csv', index_col=0)
ks200

                  종가      시가      고가      저가      거래량    변동 %
날짜
2023- 10- 31  306.33  310.52  311.51  305.81   69.93K  -0.85%
2023- 10- 30  308.95  307.10  310.09  307.01   95.85K   0.14%
2023- 10- 27  308.53  309.68  310.43  307.24   92.93M   0.25%
2023- 10- 26  307.75  311.36  312.37  307.75  110.77M  -2.76%
2023- 10- 25  316.49  319.26  319.59  316.30   91.22M  -0.61%
...              ...     ...     ...     ...      ...     ...
2022- 10- 19  291.29  293.41  295.34  290.90  110.85M  -0.78%
2022- 10- 18  293.59  293.34  293.78  289.77  117.12M   1.39%
2022- 10- 17  289.57  285.89  290.04  284.91  111.60M   0.07%
2022- 10- 14  289.36  287.59  290.32  286.59  132.07M   2.40%
2022- 10- 13  282.57  286.27  286.36  282.57  133.29M  -1.57%

[260 rows x 6 columns]

In [3]:
ks200 = ks200[::-1]
ks200

                  종가      시가      고가      저가      거래량    변동 %
날짜
2022- 10- 13  282.57  286.27  286.36  282.57  133.29M  -1.57%
2022- 10- 14  289.36  287.59  290.32  286.59  132.07M   2.40%
2022- 10- 17  289.57  285.89  290.04  284.91  111.60M   0.07%
2022- 10- 18  293.59  293.34  293.78  289.77  117.12M   1.39%
2022- 10- 19  291.29  293.41  295.34  290.90  110.85M  -0.78%
...              ...     ...     ...     ...      ...     ...
2023- 10- 25  316.49  319.26  319.59  316.30   91.22M  -0.61%
2023- 10- 26  307.75  311.36  312.37  307.75  110.77M  -2.76%
2023- 10- 27  308.53  309.68  310.43  307.24   92.93M   0.25%
2023- 10- 30  308.95  307.10  310.09  307.01   95.85K   0.14%
2023- 10- 31  306.33  310.52  311.51  305.81   69.93K  -0.85%

[260 rows x 6 columns]

In [4]:
ks200 = ks200.reset_index()

In [5]:
ks200.head(3)

             날짜      종가      시가      고가      저가      거래량    변동 %
0  2022- 10- 13  282.57  286.27  286.36  282.57  133.29M  -1.57%
1  2022- 10- 14  289.36  287.59  290.32  286.59  132.07M   2.40%
2  2022- 10- 17  289.57  285.89  290.04  284.91  111.60M   0.07%

In [6]:
ks200 = ks200[['날짜', '종가', '시가', '변동 %']]

In [7]:
ks200['변동 %'] = ks200['변동 %'].astype(str)
ks200["변동 %"] = ks200["변동 %"].str.rstrip('%')
ks200["변동 %"] = ks200["변동 %"].astype(float)

In [8]:
ks200['변동 %'] = ks200['변동 %'].shift(1)
ks200

               날짜      종가      시가  변동 %
0    2022- 10- 13  282.57  286.27   NaN
1    2022- 10- 14  289.36  287.59 -1.57
2    2022- 10- 17  289.57  285.89  2.40
3    2022- 10- 18  293.59  293.34  0.07
4    2022- 10- 19  291.29  293.41  1.39
..            ...     ...     ...   ...
255  2023- 10- 25  316.49  319.26  0.93
256  2023- 10- 26  307.75  311.36 -0.61
257  2023- 10- 27  308.53  309.68 -2.76
258  2023- 10- 30  308.95  307.10  0.25
259  2023- 10- 31  306.33  310.52  0.14

[260 rows x 4 columns]

In [9]:
ks200 = ks200.dropna()

In [10]:
ks200['종가'] = ks200['종가'].shift(1)

C:\Users\dlsgm\AppData\Local\Temp\ipykernel_10328\2144643337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ks200['종가'] = ks200['종가'].shift(1)

In [11]:
ks200['야간변화율'] = round(((ks200['시가'] - ks200['종가']) / ks200['종가']) * 100, 3)

C:\Users\dlsgm\AppData\Local\Temp\ipykernel_10328\1388436049.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ks200['야간변화율'] = round(((ks200['시가'] - ks200['종가']) / ks200['종가']) * 100, 3)

In [12]:
ks200 = ks200.dropna()
ks200.info()

<class 'pandas.core.frame.DataFrame'>
Index: 258 entries, 2 to 259
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      258 non-null    object
 1   종가      258 non-null    float64
 2   시가      258 non-null    float64
 3   변동 %    258 non-null    float64
 4   야간변화율   258 non-null    float64
dtypes: float64(4), object(1)
memory usage: 12.1+ KB

In [13]:
ks200['날짜'] = pd.to_datetime(ks200['날짜'])

In [14]:
ks200 = ks200[:251]

In [15]:
ks200 = ks200.reset_index(drop=True)

In [16]:
ks200[162:242].reset_index(drop=True)[['날짜', '변동 %', '야간변화율']].to_csv('../../train_features/ks200.csv')

OSError: Cannot save file into a non-existent directory: '..\..\train_features'