In [1]:
import pandas as pd

In [2]:
nas = pd.read_csv('../../../1. 데이터셋/train_data/NASDAQ.csv', index_col=0)
nas

                     종가         시가         고가         저가      거래량    변동 %
날짜
2023- 10- 30  12,789.48  12,750.46  12,842.96  12,691.56  801.65M   1.16%
2023- 10- 27  12,643.01  12,718.69  12,772.43  12,600.57  856.38M   0.38%
2023- 10- 26  12,595.61  12,768.97  12,818.14  12,543.86  941.24M  -1.76%
2023- 10- 25  12,821.22  13,039.86  13,042.52  12,804.30  950.80M  -2.43%
2023- 10- 24  13,139.88  13,084.99  13,170.39  13,022.85  878.12M   0.93%
...                 ...        ...        ...        ...      ...     ...
2022- 10- 19  10,680.51  10,689.31  10,808.04  10,592.88  921.13M  -0.85%
2022- 10- 18  10,772.40  10,963.99  10,972.97  10,670.12  929.62M   0.90%
2022- 10- 17  10,675.80  10,575.65  10,696.59  10,569.69  944.31M   3.43%
2022- 10- 14  10,321.39  10,742.81  10,766.68  10,308.81  918.04M  -3.08%
2022- 10- 13  10,649.15  10,131.82  10,697.71  10,088.83    1.05B   2.23%

[263 rows x 6 columns]

In [3]:
nas = nas[::-1]

In [4]:
nas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 263 entries, 2022- 10- 13 to 2023- 10- 30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   종가      263 non-null    object
 1   시가      263 non-null    object
 2   고가      263 non-null    object
 3   저가      263 non-null    object
 4   거래량     263 non-null    object
 5   변동 %    263 non-null    object
dtypes: object(6)
memory usage: 14.4+ KB

In [5]:
nas = nas.reset_index()

In [6]:
nas = nas[['날짜', '종가', '시가', '고가', '저가', '변동 %']]

In [7]:
nas['변동 %'] = nas['변동 %'].astype(str)
nas["변동 %"] = nas["변동 %"].str.rstrip('%')
nas["변동 %"] = nas["변동 %"].astype(float)

nas["시가"] = nas["시가"].str.replace(',', '')
nas["시가"] = nas["시가"].astype(float)

nas["종가"] = nas["종가"].str.replace(',', '')
nas["종가"] = nas["종가"].astype(float)

nas["고가"] = nas["고가"].str.replace(',', '')
nas["고가"] = nas["고가"].astype(float)

nas["저가"] = nas["저가"].str.replace(',', '')
nas["저가"] = nas["저가"].astype(float)

In [8]:
nas['변동 %'] = nas['변동 %'].shift(1)
nas

               날짜        종가        시가        고가        저가  변동 %
0    2022- 10- 13  10649.15  10131.82  10697.71  10088.83   NaN
1    2022- 10- 14  10321.39  10742.81  10766.68  10308.81  2.23
2    2022- 10- 17  10675.80  10575.65  10696.59  10569.69 -3.08
3    2022- 10- 18  10772.40  10963.99  10972.97  10670.12  3.43
4    2022- 10- 19  10680.51  10689.31  10808.04  10592.88  0.90
..            ...       ...       ...       ...       ...   ...
258  2023- 10- 24  13139.88  13084.99  13170.39  13022.85  0.27
259  2023- 10- 25  12821.22  13039.86  13042.52  12804.30  0.93
260  2023- 10- 26  12595.61  12768.97  12818.14  12543.86 -2.43
261  2023- 10- 27  12643.01  12718.69  12772.43  12600.57 -1.76
262  2023- 10- 30  12789.48  12750.46  12842.96  12691.56  0.38

[263 rows x 6 columns]

In [9]:
nas['당일 변동률'] = round((nas['종가'] - nas['시가']) / nas['시가'] * 100, 3)
nas['당일 변화량'] = round(nas['고가'] - nas['저가'], 3)

In [10]:
nas['당일 변동률'] = nas['당일 변동률'].shift(1)
nas['당일 변화량'] = nas['당일 변화량'].shift(1)

In [11]:
nas = nas.dropna()

In [12]:
nas = nas[1:256]

In [13]:
nas = nas.reset_index(drop=True)

In [14]:
nas['날짜'] = pd.to_datetime(nas['날짜'])

In [15]:
nas[163:245].reset_index(drop=True)[['날짜', '변동 %', '당일 변동률', '당일 변화량']].to_csv('../../train_features/nas.csv')

OSError: Cannot save file into a non-existent directory: '..\..\train_features'